### ISSUE TITLE
redirect posts as well?

### ISSUE THREAD

**Issue by rubydottxt** [bramus/mastodon-profile-redirect#6]
When I use the extension on a post page it takes me to my instance's page for that user. Would it be possible for it to take me to the page for that post? That way I'd be able to like, reply to and boost the post.

Current behaviour:
https://peoplemaking.games/@eniko => https://tech.lgbt/@eniko@peoplemaking.games
https://peoplemaking.games/@eniko/109404838700240908 => https://tech.lgbt/@eniko@peoplemaking.games

Behaviour I would like:
https://peoplemaking.games/@eniko => https://tech.lgbt/@eniko@peoplemaking.games
https://peoplemaking.games/@eniko/109404838700240908 => https://tech.lgbt/@eniko@peoplemaking.games/109404839050774368

Would that be possible? I have noticed that the numbers in my example are different on each instance, even though they refer to the same post.

**Comment by bramus** [comment]
At first I thought this wasn’t possible to the differentiating ids on each instance indeed. As pointed out in https://github.com/bramus/mastodon-profile-redirect/issues/4#issuecomment-1328018444, it turns out to be possible after all.

For (my) future reference:

```js
window.location.href = `https://front-end.social/authorize_interaction?uri=${encodeURIComponent(window.location.href)}`;
```

**Comment by bramus** [comment]
Awaiting to add this feature to the extension itself, I’ve already [added an extra bookmarklet that allows you to watch the toot on your own instance](https://github.com/bramus/mastodon-profile-redirect/tree/main/bookmarklet#view-toot).

**Comment by gon555551** [comment]
Any update on this? This feature would be great!!

**Comment by hypevhs** [comment]
@gon555551 My fork of this repo has support for redirecting to posts. I'm planning to send a PR when I get time.

**Comment by gon555551** [comment]
Nice :D Hope to use it @libjared

**Comment by bramus** [comment]
This feature has been added in 0.4.0. This new version has been uploaded to the stores, so you should get the update automatically soon.

The extension also got renamed to reflect the wider scope this extension now covers.
