### ISSUE TITLE
Add button on remote instance to follow on local isntance

### ISSUE THREAD

**Issue by lanrat** [bramus/mastodon-profile-redirect#7]
It would be great if this extension could also add a button on the remote instance to follow the account on the local instance as part of the "Follow" button or modal on the remote server.

Thanks for making such a great extension!

**Comment by bramus** [comment]
The way Mastodon generates its markup and navigates (SPA) makes it pretty difficult to consistently inject an extra button. What’s done instead, is a adjustment to the follow dialog. Upon pressing the follow button, the markup in the dialog is altered to contain a direct link to your instance.

Without the extension:

<img width="1330" alt="image" src="https://user-images.githubusercontent.com/213073/211194228-94050ef7-bd0b-452c-b061-11aadf0d816d.png">

With the extension:

<img width="1330" alt="image" src="https://user-images.githubusercontent.com/213073/211194208-bdcd619d-60a4-47a8-810a-79ecafeb108d.png">

Note the “View Profile” button that was added.

This should do it for now, but could always undergo some tweaking in the future.

**Comment by lanrat** [comment]
This is great, thanks!
